### ISSUE TITLE
DBAF - Globale Font

### ISSUE THREAD

**Issue by chfalkk** [chfalkk/DBAF#6]
Die globale Font für das Projekt wird in einer zentralen `CSS-Datei` festgelegt.
Die Datei liegt unter `src/css`

```CSS
* {
  font-family: 'Ubuntu', sans-serif;
  font-size: 20px;
}
```
